# Generated by Django 4.1.5 on 2023-01-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_tasks_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_status',
            field=models.CharField(default='Incomplete', max_length=20),
        ),
    ]
